In [99]:
import numpy as np
import cv2
import glob
import matplotlib.pyplot as plt
from scipy.optimize import minimize
%matplotlib inline

In [80]:
def estimateParams(objp,corners):
    v = []
    H1,_ = cv2.findHomography(objp,corners)
    H = H1.transpose()
    list = {(0,1),(0,0),(1,1)}
    for i,j in list:
        v.append([H[i,0]*H[j,0],H[i,0]*H[j,1]+ H[i,1]*H[j,0],H[i,1]*H[j,1],H[i,2]*H[j,0]+H[i,0]*H[j,2],H[i,2]*H[j,1]+H[i,1]*H[j,2],H[i,2]*H[j,2]])

    r1 = v[0]
    r2 = np.array(v[1])-np.array(v[2])

    
    return r1,r2,H1

    

In [81]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

out = np.zeros(shape=(26,6))
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
homography =[]
images = glob.glob('Calibration_Imgs/*.jpg')
# print(len(images))
# out = []
i=0
for fname in images:
    img = cv2.imread(fname)
#     print(fname)
#     gray = img
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (9,6),None)
#     print(corners.shape)
    
    

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners=corners.reshape(-1,2)
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)

        r1,r2,H = estimateParams(objp,corners2)
        homography.append(H)
        
        out[i] = r1
        out[i+1] = r2
        i = i+2
        
        
print(out)
# print(len(homography))
#         # Draw and display the corners
#         img = cv2.drawChessboardCorners(img, (7,6), corners2,ret)
# #         cv2.imshow('img',img)
#         plt.figure(figsize=(15,15))
#         plt.imshow(img)
#         cv2.waitKey(500)


    
    

[[-6.63195923e+01 -9.12828027e+03  4.76533311e+03 -4.66768257e-01
   5.12876079e+00  2.66685466e-04]
 [-4.83436810e+03  5.28076819e+03  1.60554618e+04  5.15121145e+00
  -7.69292791e-01 -1.31250377e-03]
 [ 4.42421532e+03 -1.13109335e+04 -9.04763376e+02  6.01743291e+00
   7.18469460e-02  1.93458431e-04]
 [-2.28942347e+04 -8.03043291e+03  5.58335875e+03  6.27389725e-01
  -5.89134901e+00  1.42776064e-03]
 [ 1.75891773e+02 -9.50080619e+03  2.62181714e+03 -2.26883734e-01
   2.48773648e+00  4.68101386e-05]
 [-7.09445966e+03  3.46976834e+03  1.20390946e+04  3.65213770e+00
  -5.32129128e-01 -4.67404910e-04]
 [ 4.05326183e+03 -1.15235054e+04 -1.02276277e+03  4.31912037e+00
   1.38458692e-01  8.10750605e-05]
 [-1.92080792e+04 -8.25614758e+03  6.88940747e+03  9.51169087e-01
  -5.09479131e+00  8.90986870e-04]
 [-2.71965489e+02 -2.89044710e+03  4.99881679e+03  3.58660075e-01
   2.63078188e+00 -1.07887176e-04]
 [-1.39647804e+03  5.62348865e+03  4.21546255e+03  2.42664988e+00
  -4.32127628e+00 -1.0461

In [98]:
# out = []
# v=[]
# print(imgpoints[0].shape)
# H,_ = cv2.findHomography(imgpoints[0],objpoints[0])
# print(H)
# # print(H[:,0])
# list = {(0,1),(0,0),(1,1)}
# for i,j in list:
#     v.append([H[i,0]*H[j,0],H[i,0]*H[j,1]+ H[i,1]*H[j,0],H[i,1]*H[j,1],H[i,2]*H[j,0]+H[i,0]*H[j,2],H[i,2]*H[j,1]+H[i,1]*H[j,2],H[i,2]*H[j,2]])

# r1 = v[0]
# r2 = np.array(v[1])-np.array(v[2])

# A = np.vstack([r1,r2])

# v=[]
# H,_ = cv2.findHomography(imgpoints[1],objpoints[0])
# # print(H)
# # print(H[:,0])
# list = {(0,1),(0,0),(1,1)}
# for i,j in list:
#     v.append([H[i,0]*H[j,0],H[i,0]*H[j,1]+ H[i,1]*H[j,0],H[i,1]*H[j,1],H[i,2]*H[j,0]+H[i,0]*H[j,2],H[i,2]*H[j,1]+H[i,1]*H[j,2],H[i,2]*H[j,2]])

# r1 = v[0]
# r2 = np.array(v[1])-np.array(v[2])

# B = np.vstack([r1,r2])

# v=[]
# H,_ = cv2.findHomography(imgpoints[0],objpoints[0])
# # print(H)
# # print(H[:,0])
# list = {(0,1),(0,0),(1,1)}
# for i,j in list:
#     v.append([H[i,0]*H[j,0],H[i,0]*H[j,1]+ H[i,1]*H[j,0],H[i,1]*H[j,1],H[i,2]*H[j,0]+H[i,0]*H[j,2],H[i,2]*H[j,1]+H[i,1]*H[j,2],H[i,2]*H[j,2]])

# r1 = v[0]
# r2 = np.array(v[1])-np.array(v[2])

# C = np.vstack([r1,r2])

# out = np.vstack([A,B,C])
# print(out)

u, s, vh = np.linalg.svd(out)
# print(s)
# print(np.argmin(s))

b = vh[5]
# print(b)
B11 = b[0]
B12 = b[1]
B22 = b[2]
B13 = b[3]
B23 = b[4]
B33 = b[5]

v0 = (B12*B13 - B11*B23)/(B11*B22 - B12**2)
lamda = B33 - (B13**2 + v0*(B12*B13 - B11*B23))/B11

alpha = np.sqrt(lamda/B11)
beta = np.sqrt(lamda*B11 /(B11*B22 - B12**2))
gamma = -1*B12*(alpha**2)*beta/lamda
u0 = gamma*v0/beta -B13*(alpha**2)/lamda


K = np.stack(([alpha,gamma,u0],[0,beta,v0],[0,0,1]))
print(K)

rmats = []
tvects = []
# print(len(homography))
for i in range(len(homography)):
    H = homography[i]
    r1 = np.matmul(np.linalg.inv(K),H[:,0])
    r2 = np.matmul(np.linalg.inv(K),H[:,1])
    r3 = np.cross(r1,r2)
    t = np.matmul(np.linalg.inv(K),H[:,2])
    # print(H[:,0].reshape(-1,1))
    R = np.column_stack([r1.transpose(),r2.transpose(),r3.transpose()])
    
    rmats.append(R)
    tvects.append(t)
    
    Ext = np.column_stack([R,t])
    P = np.matmul(K,Ext)
    error = []
    new_points = [] * len(imgpoints)
    for im_pts,model_pts in zip(imgpoints[i],objpoints[i]):
        model_pts = np.append(model_pts,1)
#         print(model_pts)
        proj_points = np.matmul(P,model_pts)
#         print(proj_points)
        x = proj_points[0]/proj_points[2]
        y = proj_points[1]/proj_points[2]
        new_points[i].append((x,y))
        err = np.sqrt((x-im_pts[0])**2  + (y-im_pts[1])**2)
        
        error.append(err)
#     print(error)
    
    mean = np.mean(error)
    print(mean)
    
    res = minimize(rosen, x0, method='nelder-mead',options={'xtol': 1e-8, 'disp': True})
    
        
        
    
    

# print(len(rmats))

[[ 2.05610659e+03 -1.01709743e+00  7.61655248e+02]
 [ 0.00000000e+00  2.04050404e+03  1.35130849e+03]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
0.8158187247511435
0.9558400843730566
0.585622697903774
0.84180476902698
0.7351960732198956
0.7187833656006469
0.675191242187761
0.48664991742952707
0.9609948504330428
0.3229648904645049
0.5676875469041626
0.738139423825101
0.6724152128428613


In [3]:
# ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)
# img = cv2.imread('left01.jpg')
# h,  w = img.shape[:2]
# newcameramtx, roi=cv2.getOptimalNewCameraMatrix(mtx,dist,(w,h),1,(w,h))

# #Using Undistort
# # undistort
# dst = cv2.undistort(img, mtx, dist, None, newcameramtx)

# # crop the image
# x,y,w,h = roi
# dst = dst[y:y+h, x:x+w]
# cv2.imwrite('calibresult.png',dst)

# #Using remapping
# # undistort
# mapx,mapy = cv2.initUndistortRectifyMap(mtx,dist,None,newcameramtx,(w,h),5)
# dst = cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)

# # crop the image
# x,y,w,h = roi
# dst = dst[y:y+h, x:x+w]
# cv2.imwrite('calibresult.png',dst)

# #Reprojection Error

# mean_error = 0
# for i in xrange(len(objpoints)):
#     imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
#     error = cv2.norm(imgpoints[i],imgpoints2, cv2.NORM_L2)/len(imgpoints2)
#     mean_error += error

# print "total error: ", mean_error/len(objpoints)

total error:  0.0208188815643
